kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ${OWNER_FILE}
        containerPath: /etc/networking-e2e-owner
        readOnly: true
networking:
  disableDefaultCNI: ${DEFAULT_CNI_DISABLED}
  ipFamily: ipv4
  podSubnet: 10.244.0.0/16
  kubeProxyMode: iptables
